// This file has been autogenerated by typings-for-css-modules. Do not modify!
export const articleCard: string;
export const thumbnail: string;
export const image: string;
export const description: string;
export const link: string;
